config/routes.rb
Rails.application.routes.draw do
    resources :questions
    resources :advertisements

    resources :topics do
        resources :posts, except: [:index]
        resources :sponsored_posts, except: [:index]
    end

    resources :posts, only: [] do
        resources :comments, only: [:create, :destroy]
        resources :favorites, only: [:create, :destroy]
        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote
    end

    resources :users, only: [:new, :create, :show]
    resources :sessions, only: [:new, :create, :destroy]

    get 'about' => 'welcome#about'

    get 'welcome/faq'

    get 'welcome/contact'

    root 'welcome#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
    has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @question = Question.all
    end

    def show
        @question = Question.find(params[:id])
    end

    def new
        @question = Question.new
    end

    def edit
        @question = Question.find(params[:id])
    end

    def create
        # #9
        @question = Question.new
        @question.title = params[:question][:title]
        @question.body = params[:question][:body]
        @question.resolved = params[:question][:resolved]

        # #10
        if @question.save
            # #11
            flash[:notice] = "question was saved."
            redirect_to @question
        else
            # #12
            flash.now[:alert] = "There was an error saving the question. Please try again."
            render :new
        end
    end

    def update
        @question = Question.find(params[:id])
        @question.title = params[:question][:title]
        @question.body = params[:question][:body]
        @question.resolved = params[:question][:resolved]

        if @question.save
            # #11
            flash[:notice] = "question was saved."
            redirect_to @question
        else
            # #12
            flash.now[:alert] = "There was an error saving the question. Please try again."
            render :new
        end
    end

    def destroy
        @question = Question.find(params[:id])

        # #8
        if @question.destroy
            flash[:notice] = "\"#{@question.title}\" was deleted successfully."
            redirect_to questions_path
        else
            flash.now[:alert] = "There was an error deleting the question."
            render :show
        end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
      </div>
      <div>
          <p> Resolved? <%= f.check_box :resolved %> </p>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% @question.each do |question| %>
   <div class="media">
       <div class="media-body">
           <h4 class="media-heading col-md-8">
               <%= link_to question.title, question %>
           </h4>
           <% if question.resolved == TRUE  %>
               <p class="media-heading col-md-8"><i>RESOLVED</i></p>
           <% end %>
       </div>
   </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
   <div class="col-md-8">
       <%= form_for @question do |f| %>
           <div class="form-group">
               <%= f.label :title %>
               <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
           </div>
           <div class="form-group">
               <%= f.label :body %>
               <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
           </div>
           <div>
               <p> Resolved? <%= f.check_box :resolved %> </p>
           </div>
           <div class="form-group">
               <%= f.submit "Save", class: 'btn btn-success' %>
           </div>
       <% end %>
   </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @question.body %></p>
  </div>
  <div class="col-md-4">
<!-- #5 -->
    <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
    <%= link_to "Delete Post", @question, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
  </div>
</div>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>